/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "martin@blom.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libdebug"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libdebug 1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libdebug"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif
